// Frontend/React/department-management/src/components/login.js
import './login.css';  
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

const Login = () => {
  // State for managing form input
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [errorMessage, setErrorMessage] = useState('');
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  // Hardcoded credentials
  const hardcodedUsername = 'admin';
  const hardcodedPassword = 'password123';

  // Use navigate to programmatically change routes
  const navigate = useNavigate();

  // Handle input change
  const handleChange = (e) => {
    const { name, value } = e.target;
    if (name === 'username') {
      setUsername(value);
    } else if (name === 'password') {
      setPassword(value);
    }
  };

  // Handle form submission
  const handleSubmit = (e) => {
    e.preventDefault();

    // Check if credentials match
    if (username === hardcodedUsername && password === hardcodedPassword) {
      setIsLoggedIn(true);
      setErrorMessage('');
      // Redirect to /departments after successful login
      navigate('/department');
    } else {
      setIsLoggedIn(false);
      setErrorMessage('Invalid credentials. Please try again.');
    }
  };

  return (
    <div className="login-container">
      <h2>Login</h2>
      {isLoggedIn ? (
        <div className="success-message">
          <h3>Welcome, {username}!</h3>
        </div>
      ) : (
        <form onSubmit={handleSubmit}>
          <div className="input-group">
            <label htmlFor="username">Username:</label>
            <input
              type="text"
              id="username"
              name="username"
              value={username}
              onChange={handleChange}
              required
            />
          </div>

          <div className="input-group">
            <label htmlFor="password">Password:</label>
            <input
              type="password"
              id="password"
              name="password"
              value={password}
              onChange={handleChange}
              required
            />
          </div>

          {errorMessage && <p className="error-message">{errorMessage}</p>}

          <button type="submit" className="login-button">Login</button>
        </form>
      )}
    </div>
  );
};

export default Login;

// Frontend/Angular/EmployeeApp/src/app/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true, // Ensure this component is standalone
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  loginError: boolean = false;

  // Hardcoded credentials (you can change these)
  private validCredentials = {
    email: 'admin@gmail.com',
    password: 'password123'
  };

  constructor(
    private fb: FormBuilder,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
    });
  }

  onLogin() {
    const { email, password } = this.loginForm.value;

    // Validate the credentials
    if (email === this.validCredentials.email && password === this.validCredentials.password) {
      // Redirect to the main page on successful login
      this.router.navigate(['all']);
    } else {
      // Show error if credentials are incorrect
      this.loginError = true;
    }
  }

  logout() {
   
    localStorage.removeItem('userCredentials'); 

    // Redirect the user to the login page
    this.router.navigate(['/']);
  }
}


<br><br><br><br><br><br>
<div class="login-container">

    
    <h2>Login</h2>
  
    <form [formGroup]="loginForm" (ngSubmit)="onLogin()">
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" formControlName="email" required />
      </div>
  
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" formControlName="password" required />
      </div>
  
      <div *ngIf="loginError" class="error-message">
        Invalid credentials. Please try again.
      </div>
  
      <button type="submit">Login</button>
    </form>
  </div>
